#!/bin/sh
set -e

VGA_STATUS=$(</sys/class/drm/card1/card1-VGA-1/status )
HDMI_STATUS=$(</sys/class/drm/card1/card1-HDMI-A-1/status )

if [ "connected" == "$VGA_STATUS" ]; then
    /usr/bin/xrandr --output VGA-1 --auto --pos 1920x1080
else
    /usr/bin/xrandr --output VGA-1 --off
fi

if [ "connected" == "$HDMI_STATUS" ]; then
    /usr/bin/xrandr --output HDMI-1 --auto --pos 1920x1080
else
    /usr/bin/xrandr --output HDMI-1 --off
fi

feh --bg-fill ~/background.jpg
